// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuOC4qoyfDP_iOnVbPpue79WnAeqNb_3Q',
    appId: '1:218983201382:web:28fb0456f471d7445ecba7',
    messagingSenderId: '218983201382',
    projectId: 'mobile-projects-aba12',
    authDomain: 'mobile-projects-aba12.firebaseapp.com',
    storageBucket: 'mobile-projects-aba12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXLSZvVcvwpMElR88zlC_DMHsCeEMAIrw',
    appId: '1:218983201382:android:e94477bd8510a1365ecba7',
    messagingSenderId: '218983201382',
    projectId: 'mobile-projects-aba12',
    storageBucket: 'mobile-projects-aba12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBscSiRol7B2MwFU8BEwcjJb-wX_0fLCY0',
    appId: '1:218983201382:ios:3fccdb1dabf96dd45ecba7',
    messagingSenderId: '218983201382',
    projectId: 'mobile-projects-aba12',
    storageBucket: 'mobile-projects-aba12.appspot.com',
    iosClientId: '218983201382-jcvpcf1ljplkvacd6b5gub1n4pamlpbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBscSiRol7B2MwFU8BEwcjJb-wX_0fLCY0',
    appId: '1:218983201382:ios:3fccdb1dabf96dd45ecba7',
    messagingSenderId: '218983201382',
    projectId: 'mobile-projects-aba12',
    storageBucket: 'mobile-projects-aba12.appspot.com',
    iosClientId: '218983201382-jcvpcf1ljplkvacd6b5gub1n4pamlpbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileProject',
  );
}
